"""opening_date to datetime

Revision ID: 55b9a986c80d
Revises: 60fa773750a3
Create Date: 2023-09-14 21:39:09.367160

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '55b9a986c80d'
down_revision = '60fa773750a3'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('accounts', 'opening_date', existing_type=sa.Date(),
                    type_=sa.DateTime(timezone=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('accounts', 'opening_date',
                    existing_type=sa.DateTime(timezone=True), type_=sa.Date())

    # ### end Alembic commands ###
