"""put back is_income to category

Revision ID: 8a7855f1d249
Revises: 0d13d7cea3ee
Create Date: 2023-09-15 11:42:08.135708

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8a7855f1d249'
down_revision = '0d13d7cea3ee'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('default_categories', sa.Column('is_income', sa.Boolean(), nullable=True))
    op.add_column('user_categories', sa.Column('is_income', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_categories', 'is_income')
    op.drop_column('default_categories', 'is_income')
    # ### end Alembic commands ###
