"""changes in transaction

Revision ID: eb7b2959e4d7
Revises: aeb10dad3be8
Create Date: 2023-09-15 11:25:06.587503

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eb7b2959e4d7'
down_revision = 'aeb10dad3be8'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transactions', sa.Column('user_id', sa.Integer(), nullable=True))
    op.add_column('transactions', sa.Column('target_account_id', sa.Integer(), nullable=True))
    op.add_column('transactions', sa.Column('amount', sa.Numeric(), nullable=True))
    op.add_column('transactions', sa.Column('label', sa.String(length=50), nullable=True))
    op.add_column('transactions', sa.Column('notes', sa.String(), nullable=True))
    op.add_column('transactions', sa.Column('is_transfer', sa.Boolean(), nullable=False))
    op.add_column('transactions', sa.Column('is_income', sa.Boolean(), server_default='f', nullable=True))
    op.drop_index('ix_transactions_short_description', table_name='transactions')
    op.create_index(op.f('ix_transactions_label'), 'transactions', ['label'], unique=False)
    op.create_index(op.f('ix_transactions_target_account_id'), 'transactions', ['target_account_id'], unique=False)
    op.create_index(op.f('ix_transactions_user_id'), 'transactions', ['user_id'], unique=False)
    op.create_foreign_key(None, 'transactions', 'accounts', ['target_account_id'], ['id'])
    op.create_foreign_key(None, 'transactions', 'users', ['user_id'], ['id'])
    op.drop_column('transactions', 'amount_in_currency')
    op.drop_column('transactions', 'short_description')
    op.drop_column('transactions', 'long_description')
    op.drop_column('user_categories', 'is_income')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_categories', sa.Column('is_income', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True))
    op.add_column('transactions', sa.Column('long_description', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('transactions', sa.Column('short_description', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.add_column('transactions', sa.Column('amount_in_currency', sa.NUMERIC(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'transactions', type_='foreignkey')
    op.drop_constraint(None, 'transactions', type_='foreignkey')
    op.drop_index(op.f('ix_transactions_user_id'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_target_account_id'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_label'), table_name='transactions')
    op.create_index('ix_transactions_short_description', 'transactions', ['short_description'], unique=False)
    op.drop_column('transactions', 'is_income')
    op.drop_column('transactions', 'is_transfer')
    op.drop_column('transactions', 'notes')
    op.drop_column('transactions', 'label')
    op.drop_column('transactions', 'amount')
    op.drop_column('transactions', 'target_account_id')
    op.drop_column('transactions', 'user_id')
    # ### end Alembic commands ###
