"""added initial_balance to Account

Revision ID: 3bb51c3bcb16
Revises: 9cd010ff4f32
Create Date: 2023-12-28 12:38:51.810710

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3bb51c3bcb16'
down_revision = '9cd010ff4f32'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('accounts', sa.Column('initial_balance', sa.Numeric(), nullable=True))
    op.execute('UPDATE accounts SET initial_balance = 0 WHERE initial_balance IS NULL')
    op.alter_column('accounts', 'initial_balance', nullable=False, existing_type=sa.Numeric())
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('accounts', 'initial_balance')
    # ### end Alembic commands ###
