"""changes in default category

Revision ID: 0d13d7cea3ee
Revises: eb7b2959e4d7
Create Date: 2023-09-15 11:27:18.442261

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0d13d7cea3ee'
down_revision = 'eb7b2959e4d7'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('default_categories', 'is_income')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('default_categories', sa.Column('is_income', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
