"""updates of Account model

Revision ID: 2971634b2f1a
Revises: 00103dd42729
Create Date: 2023-09-14 20:30:00.822542

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2971634b2f1a'
down_revision = '00103dd42729'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('accounts', sa.Column('initial_balance', sa.Numeric(), nullable=True, comment='balance at the moment of account opening'))
    op.add_column('accounts', sa.Column('show_in_operations', sa.Boolean(), nullable=True))
    op.drop_column('accounts', 'show_in_transactions')
    op.drop_column('accounts', 'initial_balance_in_currency')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('accounts', sa.Column('initial_balance_in_currency', sa.NUMERIC(), autoincrement=False, nullable=True))
    op.add_column('accounts', sa.Column('show_in_transactions', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.drop_column('accounts', 'show_in_operations')
    op.drop_column('accounts', 'initial_balance')
    # ### end Alembic commands ###
