"""empty message

Revision ID: aeb10dad3be8
Revises: 55b9a986c80d
Create Date: 2023-09-14 22:12:13.738891

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aeb10dad3be8'
down_revision = '55b9a986c80d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('accounts', sa.Column('is_hidden', sa.Boolean(), nullable=True))
    op.drop_column('accounts', 'show_in_operations')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('accounts', sa.Column('show_in_operations', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.drop_column('accounts', 'is_hidden')
    # ### end Alembic commands ###
