"""added target_amount

Revision ID: a19d7be9a717
Revises: ba93d17362b6
Create Date: 2023-09-17 19:50:55.900700

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a19d7be9a717'
down_revision = 'ba93d17362b6'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('accounts', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('accounts', 'account_type_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('accounts', 'currency_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('accounts', 'balance',
               existing_type=sa.NUMERIC(),
               nullable=False)
    op.alter_column('accounts', 'name',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    op.alter_column('accounts', 'is_hidden',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.add_column('transactions', sa.Column('target_amount', sa.Numeric(), nullable=True))
    op.alter_column('transactions', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('transactions', 'account_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('transactions', 'amount',
               existing_type=sa.NUMERIC(),
               nullable=False)
    op.alter_column('transactions', 'is_income',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('transactions', 'is_income',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.alter_column('transactions', 'amount',
               existing_type=sa.NUMERIC(),
               nullable=True)
    op.alter_column('transactions', 'account_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('transactions', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_column('transactions', 'target_amount')
    op.alter_column('accounts', 'is_hidden',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('accounts', 'name',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    op.alter_column('accounts', 'balance',
               existing_type=sa.NUMERIC(),
               nullable=True)
    op.alter_column('accounts', 'currency_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('accounts', 'account_type_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('accounts', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
