"""transaction model datetime

Revision ID: 9cd010ff4f32
Revises: 76ba1a2e993d
Create Date: 2023-09-29 12:13:07.394565

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '9cd010ff4f32'
down_revision = '76ba1a2e993d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transactions', sa.Column('date_time', sa.DateTime(timezone=True), nullable=True))
    op.drop_index('ix_transactions_datetime', table_name='transactions')
    op.create_index(op.f('ix_transactions_date_time'), 'transactions', ['date_time'], unique=False)
    op.drop_column('transactions', 'datetime')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transactions', sa.Column('datetime', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_transactions_date_time'), table_name='transactions')
    op.create_index('ix_transactions_datetime', 'transactions', ['datetime'], unique=False)
    op.drop_column('transactions', 'date_time')
    # ### end Alembic commands ###
