"""put back is_income to category

Revision ID: 444da7484090
Revises: 8a7855f1d249
Create Date: 2023-09-15 11:42:44.950419

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '444da7484090'
down_revision = '8a7855f1d249'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
