"""add table exchange_rates

Revision ID: 4b0af92d44a5
Revises: aa6f55d2c0c3
Create Date: 2024-04-14 13:14:26.532398

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '4b0af92d44a5'
down_revision = 'aa6f55d2c0c3'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('exchange_rates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('rates', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('actual_date', sa.Date(), nullable=False),
    sa.Column('base_currency_code', sa.String(length=3), nullable=False),
    sa.Column('service_name', sa.String(length=50), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), server_default='f', nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('service_name', 'actual_date', name='unique_service_date')
    )
    op.create_index(op.f('ix_exchange_rates_actual_date'), 'exchange_rates', ['actual_date'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_exchange_rates_actual_date'), table_name='exchange_rates')
    op.drop_table('exchange_rates')
    # ### end Alembic commands ###
