"""add Account.credit_limit field

Revision ID: ff674e9d4f55
Revises: a83932a8ea9a
Create Date: 2024-11-27 11:56:18.378550

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ff674e9d4f55'
down_revision = 'a83932a8ea9a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('accounts', sa.Column('credit_limit', sa.Numeric(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('accounts', 'credit_limit')
    # ### end Alembic commands ###
