"""add currency to Budget model

Revision ID: f153d2c8f8e0
Revises: 51533b59f1dd
Create Date: 2024-07-04 01:11:35.903462

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f153d2c8f8e0'
down_revision = '51533b59f1dd'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('budgets', sa.Column('currency_id', sa.Integer(), nullable=False))
    op.create_index(op.f('ix_budgets_currency_id'), 'budgets', ['currency_id'], unique=False)
    op.create_foreign_key(None, 'budgets', 'currencies', ['currency_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'budgets', type_='foreignkey')
    op.drop_index(op.f('ix_budgets_currency_id'), table_name='budgets')
    op.drop_column('budgets', 'currency_id')
    # ### end Alembic commands ###
