"""add fix of fix of fix

Revision ID: a83932a8ea9a
Revises: e15e53cd19dc
Create Date: 2024-07-04 22:47:38.620851

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a83932a8ea9a'
down_revision = 'e15e53cd19dc'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('budgets', 'name',
               existing_type=sa.TEXT(),
               type_=sa.String(length=200),
               existing_nullable=False)
    op.alter_column('budgets', 'included_categories',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.Text(),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('budgets', 'included_categories',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=100),
               existing_nullable=True)
    op.alter_column('budgets', 'name',
               existing_type=sa.String(length=200),
               type_=sa.TEXT(),
               existing_nullable=False)
    # ### end Alembic commands ###
