"""Update Transaction schema: add linked_account

Revision ID: 4ea409047b56
Revises: 620cd3aac75e
Create Date: 2024-04-09 08:59:17.938212

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4ea409047b56'
down_revision = '620cd3aac75e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transactions', sa.Column('linked_transaction_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_transactions_linked_transaction_id'), 'transactions', ['linked_transaction_id'], unique=False)
    op.create_foreign_key(None, 'transactions', 'transactions', ['linked_transaction_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('user_settings_user_id_fkey', 'user_settings', type_='foreignkey')
    op.create_foreign_key(None, 'user_settings', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user_settings', type_='foreignkey')
    op.create_foreign_key('user_settings_user_id_fkey', 'user_settings', 'users', ['user_id'], ['id'])
    op.drop_constraint(None, 'transactions', type_='foreignkey')
    op.drop_index(op.f('ix_transactions_linked_transaction_id'), table_name='transactions')
    op.drop_column('transactions', 'linked_transaction_id')
    # ### end Alembic commands ###
