"""add show_in_reports_field

Revision ID: 6c054b1d88ad
Revises: 4b0af92d44a5
Create Date: 2024-06-01 09:49:30.054169

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6c054b1d88ad'
down_revision = '4b0af92d44a5'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('accounts', sa.Column('show_in_reports', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('accounts', 'show_in_reports')
    # ### end Alembic commands ###
