"""removed old fields from models

Revision ID: d1c336f6b86c
Revises: b5f3e8e3359d
Create Date: 2024-04-11 08:17:44.499591

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd1c336f6b86c'
down_revision = 'b5f3e8e3359d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transactions', sa.Column('base_currency_amount', sa.Numeric(), nullable=True))
    op.drop_index('ix_transactions_currency_id', table_name='transactions')
    op.drop_index('ix_transactions_target_account_id', table_name='transactions')
    op.drop_constraint('transactions_target_account_id_fkey', 'transactions', type_='foreignkey')
    op.drop_constraint('transactions_currency_id_fkey', 'transactions', type_='foreignkey')
    op.drop_column('transactions', 'target_new_balance')
    op.drop_column('transactions', 'exchange_rate')
    op.drop_column('transactions', 'target_account_id')
    op.drop_column('transactions', 'currency_id')
    op.drop_column('transactions', 'target_amount')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transactions', sa.Column('target_amount', sa.NUMERIC(), autoincrement=False, nullable=True))
    op.add_column('transactions', sa.Column('currency_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('transactions', sa.Column('target_account_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('transactions', sa.Column('exchange_rate', sa.NUMERIC(), autoincrement=False, nullable=True))
    op.add_column('transactions', sa.Column('target_new_balance', sa.NUMERIC(), autoincrement=False, nullable=True))
    op.create_foreign_key('transactions_currency_id_fkey', 'transactions', 'currencies', ['currency_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('transactions_target_account_id_fkey', 'transactions', 'accounts', ['target_account_id'], ['id'], ondelete='CASCADE')
    op.create_index('ix_transactions_target_account_id', 'transactions', ['target_account_id'], unique=False)
    op.create_index('ix_transactions_currency_id', 'transactions', ['currency_id'], unique=False)
    op.drop_column('transactions', 'base_currency_amount')
    # ### end Alembic commands ###
