"""add default amount

Revision ID: 2bd570784ef2
Revises: 4ea409047b56
Create Date: 2024-04-09 20:30:11.038182

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2bd570784ef2'
down_revision = '4ea409047b56'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
