"""is_transfer by default is False.

Revision ID: b5f3e8e3359d
Revises: 8983aa792315
Create Date: 2024-04-09 21:49:39.324087

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b5f3e8e3359d'
down_revision = '8983aa792315'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
