"""add Account.is_archived field

Revision ID: 36625efa3c6f
Revises: ff674e9d4f55
Create Date: 2024-12-01 15:36:23.621629

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '36625efa3c6f'
down_revision = 'ff674e9d4f55'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('accounts', sa.Column('is_archived', sa.Boolean(), server_default='f', nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('accounts', 'is_archived')
    # ### end Alembic commands ###
