"""UserSettinngs add User relationship

Revision ID: 620cd3aac75e
Revises: aeb7c618de1e
Create Date: 2024-03-29 08:50:59.322198

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '620cd3aac75e'
down_revision = 'aeb7c618de1e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_settings', sa.Column('user_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'user_settings', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user_settings', type_='foreignkey')
    op.drop_column('user_settings', 'user_id')
    # ### end Alembic commands ###
