"""add default amount

Revision ID: 40e32f928b62
Revises: 2bd570784ef2
Create Date: 2024-04-09 20:31:22.748096

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '40e32f928b62'
down_revision = '2bd570784ef2'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
