"""new_balance can be nullable

Revision ID: 8983aa792315
Revises: 40e32f928b62
Create Date: 2024-04-09 21:46:27.692435

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8983aa792315'
down_revision = '40e32f928b62'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('transactions', 'new_balance',
               existing_type=sa.NUMERIC(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('transactions', 'new_balance',
               existing_type=sa.NUMERIC(),
               nullable=False)
    # ### end Alembic commands ###
