"""Add TransactionTemplate model

Revision ID: 02f3fc8ca59d
Revises: e1cf904bd6a1
Create Date: 2025-02-13 23:09:05.888585

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '02f3fc8ca59d'
down_revision = 'e1cf904bd6a1'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('transaction_templates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('label', sa.String(length=255), nullable=True),
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['user_categories.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_transaction_templates_category_id'), 'transaction_templates', ['category_id'], unique=False)
    op.create_index(op.f('ix_transaction_templates_label'), 'transaction_templates', ['label'], unique=False)
    op.create_index(op.f('ix_transaction_templates_user_id'), 'transaction_templates', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_transaction_templates_user_id'), table_name='transaction_templates')
    op.drop_index(op.f('ix_transaction_templates_label'), table_name='transaction_templates')
    op.drop_index(op.f('ix_transaction_templates_category_id'), table_name='transaction_templates')
    op.drop_table('transaction_templates')
    # ### end Alembic commands ###
