"""initial

Revision ID: bef87e310152
Revises: ccd31190b0de
Create Date: 2023-06-01 10:12:23.519409

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bef87e310152'
down_revision = 'ccd31190b0de'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('default_categories', sa.Column('is_income', sa.Boolean(), server_default='f', nullable=True))
    op.add_column('user_categories', sa.Column('is_income', sa.Boolean(), server_default='f', nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_categories', 'is_income')
    op.drop_column('default_categories', 'is_income')
    # ### end Alembic commands ###
